name: 'biomath-pull-request-autokey'
description: 'Annotates Pull Request description with JIRA key'
author: 'Applied Biomath, LLC'
inputs:
  github-token:
    description: 'Token used to update PR description and add labels.'
    required: true
  jira-project-key:
    description: 'Project key to use for ticket'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
